@startuml
"Secretaria" as S
"Aluno" as A
"Professor" as P
S --> (Gerar curriculo)
S --> (Armazenar informacoes)
S --> (Gerenciar disciplinas)
A --> (Realizar Matricula)
(Realizar Matricula)<. (Matricular optativa) : <<extends>>
(Realizar Matricula)<. (Cancelar Matricula): ‹<extends>>
P -->(visualizar alunos matriculados)
@enduml
