@startuml
class  Curso{
     Nome : String
     NumCreditos : int
    
}
class  Aluno{
 Periodo:int   

}
class  Turma{
    Id: int
    Disciplina:Disciplina
    Alunos: List<Aluno>
    AddAluno():void
    RemoverAluno():void
    Professor:Professor
    Período: int
    VisualizarAlunos():void

}
class  Secretaria
{
    
    gerarCurriculo(): void
    ArmazenarInformacoes(): void
    
}
class  Professor
{

    

}
class  Disciplina{
    Curso: Curso
    Nome: String
    NumeroAlunos: int
    MinimoAlunos : int = 3
    MaximoAlunos : int = 60
    Status: boolean = true
    Optativa: boolean
    verificarDisciplina():void
    exibirTurmas():void
}
class Matricula{
    Aluno : Aluno
    Curso : Curso
    Turmas: List<Turma>
    registrarAluno(Aluno alun):void
    matricular(Aluno aluno, Curso curso):void
    cancelarMatricula(Disciplina discilplina): void
    notificarSistemaCobranca(): void
    
}

abstract class Usuario{
    Nome: String
    Id: int
}

Turma "1" -- "1"Disciplina
Professor "1"-- "0..*" Turma
Matricula "1" -- "1" Aluno
Turma "1" *-- "0..*"Aluno
Curso "1"-- "0..*"Disciplina
Usuario <|-- Aluno
Usuario <|-- Professor
Usuario <|-- Secretaria

@enduml